### ISSUE TITLE
_thread library needs updating

### ISSUE THREAD

**Issue by goatchurchprime** [MZachmann/LightLora_MicroPython#1] opened 2018-03-19 17:32 UTC
I'm not good with this pull request technology.  I got it working (I think) with, in sx127x.py:

		self._lock = _thread.allocate_lock()

and then:

	def acquire_lock(self, lock=False):
		if self._lock:
			if lock:
				self._lock.acquire()
			else:
				self._lock.release()

Also, I think it would be easier for folks if it indented with spaces instead of tabs

**Comment by MZachmann** [comment] 2018-03-20 11:48
Thanks for the comments. The problem is that I'm using the [loboris MicroPython](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo) implementation and it supports this non-standard syntax. See https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/thread.

Otherwise you are absolutely correct. Your syntax is the standard. I can check for existence of allocate_lock vs lock and dynamically test. I'll take care of that and try to test with stock MicroPython.

As for tabs. I know that Linux folks don't like them but:

- I spent two hours debugging spaced python that had a tab I didn't see on-screen. The code kept failing to run because it saw an uneven line and the error message was screwy. Bah.
- Tabs are efficient and every byte counts on my memory-constrained chips.
- With tabs I can, with one click, visually shrink the indents for fitting into blogs and word docs. Meanwhile my code view is very neat.

So, I'm not convinced on the spaces vs tabs thing, but I appreciate your viewpoint.

**Comment by MZachmann** [comment] 2018-03-20 13:41
Added new code and tested against both the Loboris and the standard Micropython builds so I'll close this in a bit.

**Closed as completed** 2018-03-27 11:41 UTC
